name: tagged-release
on:
  push:
    branches:
      - "main"
    tags:
      - v*
jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build
        run: make main

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            *.zip
            all_songs.txt
            hashed_*.txt
